### ISSUE TITLE
프로젝트의 큰 방향성 정하기

### ISSUE THREAD

**Issue by Yoonkimove** [BLUENCE/M5_Idol_lyrics#1]
프로젝트의 이유에 대한 선정
(아래 네 가지 질문에 각자 대답해 보기)
1. 가사로부터 무엇을 분석하고 싶은가?
2. 이 프로젝트를 하는 이유 (지향점)
3. 왜 하필 가사를 분석했냐? 
4. 왜 하필 아이돌을 분석하냐?

**Comment by Yoonkimove** [comment]
1. 가사로부터 무엇을 분석하고 싶은가?
   1. 여자 아이돌과 남자 아이돌 비교 분석
      1. 가장 많이 등장하는 단어
      2. 주제 별로 분류하고 각 주제 안에서의 표현 양식 비교
      3. 작사가 성비 분석
      4. 같은 작사가가 여남 아이돌 모두에게 가사를 주었을 때 둘을 비교
      5. 남자 작사가가 여자 아이돌에게 준 가사 & 여성 작사가가 남자 아이돌에게 준 가사 비교(갯수, 내용)
      6. 아이돌 그룹 멤버가 직접 작사한 가사 분석
   2. 작사가 별 가사 분석
      1. 활발히 활동한 작사가의 가사 분석(이는 여성 작사가에 한정)
   3. 한 사람이 작사, 작곡에 모두 참여한 경우 모아보기
2. 이 프로젝트를 하는 이유
   현재 가사에서 문제 의식을 느꼈다. 여자 아이돌의 가사는 수동적이거나 성적으로 어필하는 가사가 많다고 느꼈다. 반면 남자 아이돌의 가사는 능동적이고 자아가 강하며 도전이나 성장 등을 이야기한다. 또한 둘 다 성역할/성고정관념을 강화하는 가사가 많은데, 여자는, 남자는 ~하다, ~해야 한다 등의 가사가 많이 등장한다. 
   여자 아이돌을 중심으로 분석하고 싶은데, 그 이유는 보다 진취적이고 능동적인 여성상을 표현하는 가사가 많이 나오기를 바라기 때문이다.
3. 왜 하필 가사를 분석하냐?
   대중음악의 가사가 사람들에게 미치는 영향이 크다고 생각한다. 대중음악은 파급력이 크다. 쉽게 따라부를 수 있고, 어디에서나 쉽게 들을 수 있다. 노래를 듣다 보면 흥얼거리게 되고, 무의식적으로 반복해서 부르게 되면 그 안에 있는 내용 또한 쉽게 받아들이게 된다. 처음에는 불편하다고 생각되어도 익숙해지면 문제점을 느끼기가 쉽지 않다.
   그렇지만 가사는 분명히 우리에게 어떤 메세지를 전달한다. 이는 특히 자아가 형성되는 시기의 10대들에게는 더 큰 영향을 끼친다. 
   예를 들어 트와이스의 'CHEER UP'의 가사
       여자가 쉽게 맘을 주면 안돼
       그래야 니가 날 더 좋아하게 될걸
       태연하게 연기할래 아무렇지 않게 
       내가 널 좋아하는 맘 모르게 
   는 여자는 좋아하는 감정이 있음에도 거절하는 것으로 묘사하고, 이는 여성의 거절 의사 표시를 존중하지 않아도 된다는 메세지를 전달하게 된다.
   가사 분석을 해 봄으로써 그냥 지나칠 수 있는 가사들을 비판적으로 들여다볼 수 있는 기회를 제공하고자 한다.
   
4. 왜 하필 아이돌을 분석하냐?
   아이돌은 10대에게 큰 영향을 미친다. 특히 큰 팬덤을 가진 아이돌은 팬들에게 큰 영향력을 가지고 있다. 또한 현재 가요 시장은 아이돌이 차지하는 비중이 굉장히 크다. 발라드, 힙합 등의 장르를 제외하고 댄스 음악의 대부분은 아이돌 음악이다. 또한 아이돌 대부분은 동성으로 구성되어 있는 그룹인데, 타겟층이 명확하고 이에 따라 팬덤이 형성된다는 특징이 있어 이들의 성별에 따라 가사의 차이가 명확할 것이라는 가정 하에 분석을 계획했다.

**Comment by gabining** [comment]
1. 연도별 아이돌의 가사 변화 양상과 남자/여자 아이돌별 가장 자주 나오는 가사 구성 형태 분석
2. k-pop을 주로 소비하는 층(외국인/10대 등)에게 가사에서 자주 쓰이는 단어 및 구성이 어떤 형식으로 이루어져 있는지를 시각화하고자 한다. 이를 통해 문제의식을 가질 수 있도록 하고 싶다.
3. 예전부터 노래 가사는 무언가 말하고 싶은 것을 전달하는 도구로 인식된다.  이러한 관점에서, 특히나 대중에게 파급력이 큰 그룹의 가사의 경우 많은 사람들이 자연스레 흥얼거리며 소비를 하게 된다. 따라서 이를 분석함으로서 남자와 여자 아이돌 가사의 차이점을 드러내보고 싶다.
4. 한국어를 잘 모르는 외국인과 아직 자아나 가치관이 제대로 정립되지 않은 10대들에게 아이돌이 미치는 영향이 클 것이라 생각. 따라서 아이돌을 주제로 프로젝트를 진행하고자 한다.

**Comment by jyw7664** [comment]
1. **가사로부터 무엇을 분석하고 싶은가?**
   - 작사가와 여돌남돌의 관계 시각화
   - 한작사가가 남돌에게 가사를 줄 때와 여돌에게 가사를 줄 때 어떤 갭이 있을지
   - 여돌과 남돌이 말하는 여성과 남성의 정의 도출해보기
   - 여돌은 사랑노래가 더 많고 남돌은 사회비판, 도전이 많은가?
   - 직접 작사와 작곡을 하는 아이돌로 알려진 것은 주로 남자 아이돌이다. 여자아이돌의 프로듀싱은 정말 적을까? 여돌은 수록곡으로, 남돌은 타이틀로 나가는 경우가 많지 않을까?

2. **이 프로젝트를 하는 이유, 지향점은 무엇인가?**
   - 이전까지의 아이돌, 대중가요의 가사분석은 시대적, 사회적으로 변화된 형태를 중점적으로 분석한 경우가 대부분이었다. 우리는 남자아이돌과 여자아이돌의 가사를 중점적으로 비교분석해보며 성별에 따라 가사가 어떤 식으로 표현되는지 분석한다.
   - 또한 노래가사속의 여성혐오로 논란이 되었던 그룹들이 상당히 있다. 아이돌이 직접 작사활동에 참여하지 않더라도 어떤 가사의 곡을 노래하는지, 어떤 안무를 선보이는지에 대한 책임이 있을 것이다. 우리는 아이돌의 가사속에서 이러한 문제점들을 꼽아 보면서 작사가에게는 창작사로서의 책임을, 가수에게는 직접적으로 대중에게 가사를 전달하는 책임을 묻고 건강한 비판을 하고자 한다.

3. **왜 하필 가사를 분석하나?**
   - 최근 아이콘의 '사랑을 했다' 가 쉬운 멜로디와 단어덕분에 어린이들의 떼창곡으로 주목를 끌었다. exid의 '위아래' 같은 경우도 마찬가지이다. 아이돌의 노래가 쉬운멜로디를 가지기만 한다면 선정성을 띄는 노래가사들과 춤이 어린이들에게까지 쉽게 노출되는 것이다. 
   - 90년대 여자 아이돌의 스타일은 당당함과 어른스러움(섹시컨셉이어도 주체적인 이미지를 내세움)을 내세웠다. 반면 최근 여자아이돌은 수동적인 섹시컨셉을 밀고 나가거나, 청순을 넘어 유아틱해지는 것을 확인 할 수 있었다. 이런 변화를 가사를 통해 분석 할 수 있을 것이다.

4. **왜 하필 아이돌을 분석하나?**
   - ~위 두분과 의견이 비슷하여 생략합니다:smile:~

**Comment by chacha816** [comment]
1. 가사로부터 무엇을 분석하고 싶은가?

- 아이돌 노래에서 가장 많이 등장하는 단어와 내용
- 시대별 아이돌 가사의 특성 비교 
  (예를들면 반복성이 있는 가사가 많다던가, 영어가 사용빈도가 높다던가, 사랑노래나 이별노래가 유독 많다던가 등등)
- 외래어(영어)사용 빈도 시각화 (외래어를 가장 적게 사용하는 아이돌도 궁금하다.)
- 여자 아이돌과 남자 아이돌 가사의 표현방식
- 흔히 말하는 아이돌 히트곡의 가사는 어떤 내용이 가장 많을까?
- 여자아이돌 노래는 여성작사가가 더 잘 쓰고, 남자아이돌 노래는 남성작사가가 더 잘 쓸까?
- 소속사별 가사 특징 비교

2. 이 프로젝트를 하는 이유 (지향점)

- 최근 몇년 사이에 K-POP은 세계적으로 주목을 받고있다. K-POP의 중심은 아이돌 이라고 할 수 있는데, 이러한 아이돌들의 가사에 나타나는 문제점을 알아보고자 한다.  가사가 남녀에 따라 얼마나 다르게 나타나는지, 아이돌에 영향을 많이 받는 10대들에게 어떤 영향을 주는지 알아보고싶다.

3. 왜 하필 가사를 분석했냐?

- 같은 멜로디의 음악이라도 어떻게 가사를 붙이느냐에 따라 이별 노래가 될 수도 있고, 사랑 노래가 될 수 도 있다.  가사가 없는 멜로디는 감정만 움직이게 하지만 가사가 붙으면  감정 뿐만 아니라 생각이나 내용을 전달할 수 있다. 이처럼 가사는 사람에게 전달되는 영향력이 크기 때문에, 대중에게 영향력이 큰 아이돌들의 가사를 분석해서 문제점을 알리고 경각심을 가질 필요가 있다는 것을 전달하고 싶다.

4. 왜 하필 아이돌을 분석하냐?

- 아이돌은 국내 뿐만 아니라 해외에서도 다른 가수들보다 인지도가 높고, 영향력이 크기 때문이다. 
  (저도 위에 분들과 생각이 비슷해서 간단히 쓸게요!)

**Comment by BLUENCE** [comment]
1. 가사로부터 무엇을 분석하고 싶은가?

- 작사가별 가사의 패턴분석 (주제, 여성상, 남성상, 지향성, 자주사용되는 단어, 외래어, 특징)

- 소속사별 패턴분석 (세부내용은 위와동일)

- 패턴분석을 통한 작사가별, 소속사별 가사 생성머신 시스템 제안


2. 이 프로젝트를 하는 이유

- 자연어처리에 대한 미친(...) 흥미
- 데이터를 활용하여 정량적으로  과학적으로 분석한 결과를 토대로 아이돌산업의 건강한 비판과 현대의 여성상과 남성상에 대한 차이를 알아보고  나온 결과를 쉽고 간결하게 시각화하여 전달하고 싶습니다.
